#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CDIR="${DIR%??????}"
cd $CDIR/Resources ||exit
./TMSmono/Versions/6.8.0/bin/mono-sgen64 TTMM/TerraTechModManager-GTK.exe
